version: '3.4'

services:
  mad-expences-tracker-db:
    image: "mongodb/mongodb-community-server"
    container_name: mad-expences-tracker-db
    ports: 
      - "27017:27017" 
    volumes:
     - './data:/data/db'

  mad-expences-tracker-back:
    depends_on: [mad-expences-tracker-db]
    container_name: mad-expences-tracker-back
    build:
      context: ./Server
      dockerfile: dockerfile
    ports:
        - "5443:5443"
    environment:
      - "DB_IP=mad-expences-tracker-db"
      - "DB_PORT=27017"
  
  mad-expences-tracker-ui:
    depends_on: [mad-expences-tracker-back]
    container_name: mad-expences-tracker-ui
    build:
      context: ./Client
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    environment:
      - "VITE_SERVER_IP=mad-expences-tracker-back"
      - "VITE_SERVER_PORT=5443"


  