FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 5443

ENV ASPNETCORE_HTTP_PORTS 5443
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["MadExpenceTracker.Server/MadExpenceTracker.Server.csproj", "MadExpenceTracker.Server/"]
COPY ["MadExpencesTracer.Core/MadExpenceTracker.Core.csproj", "MadExpencesTracer.Core/"]
COPY ["MadExpenceTracker.Persistence/MadExpenceTracker.Persistence.csproj", "MadExpenceTracker.Persistence/"]
RUN dotnet restore "./MadExpenceTracker.Server/./MadExpenceTracker.Server.csproj"
COPY . .
WORKDIR "/src/MadExpenceTracker.Server"
RUN dotnet build "./MadExpenceTracker.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./MadExpenceTracker.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MadExpenceTracker.Server.dll"]